### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by saneyuki** [karen-irc/karen#15]
- [x] new forked project name
- [x] support environments
- [ ] setup
  - [ ] how to launch
- [x] license
- [ ] how to contribute
  - [ ] how to test

**Comment by saneyuki** [comment]
This is depend on #16
